### ISSUE TITLE
Question:Due to missing external tools the following constraints were ignored:cross_dimerization,secondary_structure,self_dimerization

### ISSUE THREAD

**Issue by YangLeng90** [matdoering/openPrimeR#10]
According to  https://www.bioconductor.org/packages/release/bioc/vignettes/openPrimeR/inst/doc/openPrimeR_vignette.html and try to reproduce the result inside.

when run :

`
settings.xml <- system.file("extdata", "settings", "C_Taq_PCR_high_stringency.xml", package = "openPrimeR")
settings <- read_settings(settings.xml)
`
It reoprt :Due to missing external tools the following constraints were ignored:cross_dimerization,secondary_structure,self_dimerization.
But I have already installed MELTING, ViennaRNA ,OligoArrayAux ,MAFFT and  Pandoc.

Cheack the` settings@Input_Constraints@status`:
 cross_dimerization, secondary_structure,self_dimerization  were seted as FALSE

**Comment by matdoering** [comment]
If dimerization and secondary structure calculations are not possible this is due to missing executables or incorrect versions for OligoArrayAux and ViennaRNA. To debug your issue, please have a look at the checks that are performed to identify the correct Installation of the tools:

https://github.com/matdoering/openPrimeR/blob/master/R/zzz.R

Most importantl, the tool executables must be in your PATH. If you have issues solving the problem you can also use the docker image of openPrimeR, which contains all dependencies: 

https://hub.docker.com/r/mdoering88/openprimer/

**Comment by YangLeng90** [comment]
Thank you very much; At your suggestion, I have solved this issue. 
 Another question: 
Is ther any parameters in XML setting file to set  multiplex PCR Amplicon length

**Comment by matdoering** [comment]
The amplicon length can't be set as an explicit parameter but you can set the allowed binding region for forward and reverse reads in the templates that you have loaded.

**Comment by YangLeng90** [comment]
Thank you for you reply
When I run:
`optimal.primers <- design_primers(template.df[1:2,], mode.directionality = "fw",
                                  settings = design.settings)`
It report an error: task 1 failed ,can't open the connection, because it can not find the met_seq**.result.csv
I have saw the souce code of con_melting_temperature.R at line 293
`result.file <- paste(out.file, ".results.csv", sep = "")`
but I can't find where to generate this file

**Comment by matdoering** [comment]
Looks like `melting-batch` isn't working correctly. Can you check if you can run it independently?

**Comment by YangLeng90** [comment]
After installed melting,  I can only find melting command and there is no melting-batch, so I create a soft link  melting-bach to melting
