### ISSUE TITLE
constraints were ignored:cross_dimerization,self_dimerization

### ISSUE THREAD

**Issue by warthmann** [matdoering/openPrimeR#5]
Hello,
I have have all dependencies installed, most of them via conda, including oligoarrayaux (3.8). Only Melting needed to be installed separately. I am pointing R to the respective /bin directories, I am setting the UNAFOLDDAT variable to the respective /share directory. 

_>library(openPrimeR)_ 
does not complain about missing dependencies and yet upon

_> settings <- read_settings(settings.xml)_

I get 

_Reading settings file: C_Taq_PCR_high_stringency.xml
Due to missing external tools the following constraints were ignored:cross_dimerization,self_dimerization_

I understand that this is related to oligoarrayaux, which is installed and in the path. Can you please tell me which particular binary openprimer is looking for and is missing? Maybe the conda version does not have all binaries?

thank you very much for your time. I am using R 4.0.2 on MacOSX through Studio 1.3.959.

best
Norman

**Comment by matdoering** [comment]
There was a bug with the checks for oligoarrayaux, leading to a direct error in case that UNAFOLDDAT is not set, although the tool may still work.

Another possible reason for this problem is that the user has defined the UNAFOLDDAT variable using `Sys.setenv("UNAFOLDDAT=...")` , which will not be available when `hybrid-min` is called (due to the behavior of `Sys.setenv`). Therefore, the UNAFOLDDAT must be set before starting openPrimeR using the `PATH` variable like so:

```
export UNAFOLDDAT=...
R
library(openPrimeR)
```
